### PR TITLE
Resolved conflicts for merging pull request #97 into dev branch

### PR DESCRIPTION
**Pull request by james-prior**
I made many many changes to resolve the conflicts,
so it is inevitable that I created at least one bug,
so please test it.

This is for merging into dev branch instead of master branch.

### CODE REVIEW

**Comment by PedroSFreitas** [comment]
@james-prior 
Not sure if I can accept this pull, because it link to https://github.com/mayaculpa/hapi/pull/102/commits/e060e03c17c0270dfd18d2fc66ce4c26c2d10575
Is that correct?

**Comment by PedroSFreitas** [comment]
@james-prior 
Another thing, do you mind merging jp-43-1 as well? So we can close https://github.com/mayaculpa/hapi/pull/92? Since you are going to change this pull probably...

**Comment by james-prior** [comment]
@PedroSFreitas wrote:

> @james-prior
> Not sure if I can accept this pull, because it link to e060e03
> Is that correct?

Even though e060e03 has undesired bogus code,
e060e03 was merged to resolve pull request #92 
knowing that a later commit ab233cb is even better.
Study [diffs for ab233cb](https://github.com/mayaculpa/hapi/pull/102/commits/ab233cbe38c70cc264cc9edd9a37d2f7a660cfc7).

@PedroSFreitas wrote:

@james-prior
> Another thing, do you mind merging jp-43-1 as well? 
> So we can close #92? Since you are going to hange this pull probably...

When you accept this pull request,
since jp-43 and jp-43-1 are parents in the long chain of commits for
this pull request,
accepting this pull request will automatically resolve (and close) pull request #92.

**Comment by james-prior** [comment]
By the way, accepting this pull request
should resolve pull request #97 also
since 31d6cfd is a parent of jp-50

In other words, accepting this pull request will resolve three pull requests:
1. this pull request
2. pull request #92 
3. pull request #97

**Comment by PedroSFreitas** [comment]
Perfect. Thanks.

**Pull request merged**
