### PR TITLE
communicator.py: Remove redundant str().

### PR DESCRIPTION
**Pull request by james-prior**
%s performs str() in all of the following.
The explicit str() in the first one is redundant.
The comma in the last one is allowed by the logging module, IIRC.

    self.logger.info("Connected with result code %s" % str(rc))
    self.logger.info("Connected with result code %s" % rc)
    self.logger.info("Connected with result code %s", rc)

### CODE REVIEW

**Comment by PedroSFreitas** [comment]
It won't work for now, I believe.

Standard logging module allows variable argument. Unfortunately (?) in one of our attempts to find the source of the leaking problem, I wrote a small (dumb) logging implementation* that doesn't accept vararg. But I'm sure we'll get back to the standard since we have narrowed down the problem somewhere around MQTT and Scheduler.

*we saw some comments about memory leaking using standard logging on a multi threaded application (in our case the Scheduler).

**Comment by james-prior** [comment]
Oh, I did not catch that you were not using standard library.

So I backed off to self.logger.info("... %s" % rc) with new commit.

**Comment by james-prior** [comment]
I added *args support to Log.info(), so I restored the call to ...("... %s", rc).

Python's support of varargs is so much easier than C's.

**Comment by james-prior** [comment]
Added *args support to Log.exception() also.

Use *args much in calls.

**Pull request merged**
