### PR TITLE
many improvements for rtc_interface.py

### PR DESCRIPTION
**Pull request by james-prior**
I had read-only access for a few days, so now I'm catching up.
This pull request should be easy for you to merge since I already did the tedious merging.

There are many improvements. Two significant ones are:

1. Greatly simplified reading and writing EEPROM.
2. Simplifed handling of imports that might fail to import.

### CODE REVIEW

**Comment by PedroSFreitas** [comment]
👍 for the "I already did the tedious merging".

**Comment by james-prior** [comment]
PedroSFreitas wrote:

> 👍 for the "I already did the tedious merging".

[meld](http://meldmerge.org/) is a very helpful tool for comparing and merging different versions of a file.

**Comment by PedroSFreitas** [comment]
Thanks, I'll check that out. 👍

**Comment by james-prior** [comment]
When first playing with meld, just compare two files. For example,

    meld rtc_interface-old.py rtc_interface-new.py

Then advance to using meld with git stuff. I use the following gmd script to help use meld with git.

    jp@happy:~$ cat ~/bin/gmd
    #!/bin/sh

    # Does git diff with external diff program,
    #     even if diff=whatever is not specified in .gitattributes
    #     even if [diff "whatever"] is not specified in ~/.gitconfig.

    GIT_EXTERNAL_DIFF=git-ext-diff-wrapper git diff "$@"
    jp@happy:~$ cat ~/bin/git-ext-diff-wrapper
    #!/bin/sh

    # showargs "$@"
    meld "$2" "$5"
    jp@happy:~$ 

bon appétit

**Comment by PedroSFreitas** [comment]
Great, James. Thanks again!
I'll definitely use it, and probably your script as well! 😄

**Pull request merged**
