### PR TITLE
Fixing log call, 'finally' to close db connections and broker discovery changes.

### PR DESCRIPTION
**Pull request by PedroSFreitas**
I'd like some attention to "discover" function in smart_module.py. I've tried to make it as clean as possible, removing anything that wasn't necessary. However I'm not at all happy with the use of "time.sleep()" function.
Any thoughts?

ps.: trying to find some time between classes.

### CODE REVIEW

**Comment by PedroSFreitas** [comment]
https://github.com/mayaculpa/hapi/pull/95/commits/bd2052bbdf1f9f4c0830615671f11608943e8e8c#diff-7986d6de03907e409212760566d8a953R600

> And of course: "The current code keeps the CPU running all the time."

This was a good approach to remove "delay()" call on Arduino.
But I believe the same principal cannot be applied to a small piece of code inside a function that needs to continue only after the discovery process is complete.

Anyway, I'd like some tips. 😄

**Comment by james-prior** [comment]
@PedroSFreitas 

> This was a good approach to remove "delay()" call on Arduino.
> But I believe the same principal cannot be applied 
> to a small piece of code inside a function 
> that needs to continue only after the discovery process is complete.

Often, it can be done. Often it is tedious to do so with traditional
coding techniques, such as state machines, 
whether event driven or polled.
Hence the popularity of asynchronous frameworks
and multitasking operating systems.
We have it so good with Python and Linux.
C(++) on bare hardware is more work.

Incremental improvements are good, 
even when they do not resolve everything.
Since you recognize what is undesirable, 
you will be looking for the "right way".
You will be happy when you figure out the "right way".
Some times it takes a long time to find that "right way".
Until then we are glad for incremental improvements.

**Comment by james-prior** [comment]
I finally got around to reviewing your pull request.
It got easier when I ignored the stuff in 9d8b997.

The most interesting changes are in 65ea8bf and 751ef4e
where you close the database or zeroconf in the finally clauses.

What would happen in the finally clause 
if sqlite3.connect() or Zeroconf() provoked an exception,
so database or zeroconf was undefined?
[updated:]
Is that no worse that what the code did before these commits?

I wonder about context handlers versus try/except/finally.
What can we learn from Raymond Hettinger's presentation
[Best practices for beautiful intelligible code](http://pyvideo.org/pycon-us-2015/beyond-pep-8-best-practices-for-beautiful-inte.html)?

**Comment by james-prior** [comment]
I wonder if and hope that Zeroconf() and sqlite3.connect() support context managers.

**Comment by james-prior** [comment]
Earlier I wrote:

> I wonder if and hope that Zeroconf() ... support context managers.

I scanned zeroconf source code and found no instance of \_\_enter__ or \_\_exit__.
That is not encouraging for zeroconf supporting context managers.
We could 
- add context manager support to zeroconf,
- or create a wrapper object for context manager without changing zeroconf itself,
- or continue to use the finally clause stuff.

**Comment by PedroSFreitas** [comment]
> so database or zeroconf was undefined?

Not sure if this can happen. If it is undefined by the time the code reaches the finally block, probably an exception already happened before (when using the connect or zeroconf call)? Not sure though...


> What can we learn from Raymond Hettinger's presentation
> Best practices for beautiful intelligible code?

Thanks, I will watch it as soon as possible.
And then I'll be able to answer your last comment, I believe.

**Comment by james-prior** [comment]
@PedroSFreitas wrote: 

[> > @james-prior wrote]:

> > so database or zeroconf was undefined?

> Not sure if this can happen. 
> If it is undefined by the time the code reaches the finally block, 
> probably an exception already happened before 
> (when using the connect or zeroconf call)? Not sure though...

Looking at try/except/finally block in SmartModule.discover() of 65ea8bf,
if the call to Zeroconf() fails, it would raise an exception that would be
caught and handled by the except clause and zeroconf would not have a value.
When the finally clause executes after the except clause,
the zeroconf.close() statement would raise a NameError exception because
zeroconf is not defined.

That said, it probably does not matter.
Both 8dcbe17 and 65ea8bf versions would both crash if Zeroconf() fails.
They just crash in different places with different exceptions.
The previous version 8dcbe17, 
would just crash immediately if Zeroconf() raised an exception.

I think it's unlikely that Zeroconf() would raise an exception for something
other than a programming error, so it is probably good for the program 
to crash if Zeroconf() were to raise an exception.

---

Separately, I looked at the 65ea8bf version yesterday, 
especially of SmartModule.discover() and things are complicated.
I studied the source code for zeroconf and studied threads. 
I came to no conclusions and just had more and more questions for myself.

I am guessing that you would like to wait for the first of either 
two things:
1. timeout expires (currently time.sleep(max_sleep_time))
in which case one becomes the mqtt server
2. zeroconf finds an mqtt server 
in which case one uses the first mqtt server found

I don't know what the clean way to do that is.

**Comment by PedroSFreitas** [comment]
> I don't know what the clean way to do that is.

Yeah.
For now, I believe we could just leave in this way and move forward. Then we will have more time to test it running on real modules (devices) as well as time to think about the best way to handle all this. Right?
Thanks a bunch @james-prior 

I'll be merging this pull and the previous ones.

**Comment by james-prior** [comment]
On Mon, 12 Jun 2017 05:59:27 -0700, Pedro Freitas <notifications@github.com> wrote:

> For now, I believe we could just leave in this way and move forward.

Sounds good.

**Pull request merged**
