### PR TITLE
READ THE FULL COMMIT MESSAGE. Do not merge this commit.

### PR DESCRIPTION
**Pull request by james-prior**
The point of this is to think about readability.

Do not merge this commit.
Study this commit's parents, which are summarized below.

    jp-43-0 if (0 < pinControl[i] && pinControl[i] < 5) {
    jp-43-1 if (1 <= pinControl[i] && pinControl[i] <= 4) {
    jp-43-2 if (UNUSED_PIN < pinControl[i] && pinControl[i] < ANALOG_INPUT_PIN) {
    jp-43-3 if (DIGITAL_INPUT_PIN <= pinControl[i] && pinControl[i] <= ANALOG_OUTPUT_PIN) {

They cover the combinations of:

    < versus <=
    raw numbers versus names

Are all the parents correct?
For each parent, what do you like or dislike?
Which parent is the most readable to you?
Please merge whichever parent is most readable to you.

### CODE REVIEW

**Comment by TylerReedMC** [comment]
The numbered versions are much more readable. The ordering of pin modes is arbitrary; there's no logic to it other than it's the way Mark Miller decided to order them a few years ago. So saying some pin mode is between UNUSED_PIN and ANALOG_PIN is akin to saying that some variable is between PAPER_CLIPS and SHOPPING_BAGS.

I would say that I prefer 1 <= pinControl[i] && pinControl[i] <= 4 as it makes the programmer think about the ordering of the modes and does not include values that are outside of the numbers used in the ordering.

**Comment by james-prior** [comment]
@TylerReedMC wrote:

> The numbered versions are much more readable.

Thanks for the clarity.

> ... I prefer 1 <= pinControl[i] && pinControl[i] <= 4 ...

Earlier I wrote:

>     jp-43-1 if (1 <= pinControl[i] && pinControl[i] <= 4) {

Merging jp-43-1 would be as you wish.

**Comment by PedroSFreitas** [comment]
Okay, I got a bit lost here.
Was this already addressed on another pull?

Edit: should we close this pull if so?

**Comment by james-prior** [comment]
@PedroSFreitas asked:

>  Was this already addressed on another pull?

No. We are waiting for @TylerReedMC to merge jp-43-1.
After merging jp-43-1 it would be time to close this pull request.

**Comment by james-prior** [comment]
@james-prior wrote:

> We are waiting for @TylerReedMC to merge jp-43-1.

It does not matter who merges jp-43-1.

**Pull request merged**
