### PR TITLE
Reworked some timekeeping

### PR DESCRIPTION
**Pull request by james-prior**
Enough code was changed, that something is broken,
so it need to tested and debugged.

Got rid of delay() call in loop()!

Need to get rid of most if not all long delay() calls elsewhere.

### CODE REVIEW

**Review by ozarchie — COMMENTED** [review]
The reason that the factor was 10 was that the loop had a delay at the end. So the loop only executed once every 100mS - so 10*100 = 1000mS. It was really just a placeholder until proper time functions and delay() functions were implemented.

**Review by ozarchie — COMMENTED** [review]
As I commented previously, the control of lamps is quite different to control of pumps. It may be that the way in which lamps, (especially sodium vapour lamps) turn on has the be monitored differently. We need to maintain separation of these. My suggestion before was that if we went to a common piece of code, that a definition of the parameters of that code was set (e.g. turn-on time, duration, turn-off time etc)

**Review by ozarchie — COMMENTED** [review]
The reason for the delay() is to reduce the number of polls to approximately 10/s. With the proposed timer revisions, this would change to event driven. Delay() is actually a lower power mode that continually polling.

**Comment by james-prior** [comment]
First, the backdrop:

[You aren't gonna need it](https://en.wikipedia.org/wiki/YAGNI) aka YAGNI.

This is a tough one for experienced programmers,
especially myself, who say:

> "But I **know** that I **am** going to need it.".

YAGNI is an exaggeration for emphasis. The plain way of saying it is.

> When you need some code, go ahead and write it, 
> **but not until you actually need it**.

Prediction is difficult, especially of the future.
Often the future turns out differently than anticipated. That is key. 
Adding stuff for the anticipated future affects other code.
So the code that was added or changed for what was anticipated, 
turns out to be either unnecessary or has to be changed. 
The effect cascades through code.
Code that is never used or never used as written, 
wastes time writing it, and wastes time reading it,
and introduces little (and sometimes not so little) 
complications elsewhere to accommodate it.
The indirect unnecessary complications are particularly pernicious.

The YAGNI approach avoids the problems of wasted time and unnecessary complexity. 
YAGNI does this by not coding stuff until actually needed, 
even when (or **especially when) one knows** it will be needed in the future.

> As I commented previously, the control of lamps is quite
> different to control of pumps.

I wrote commit 173f039, while remembering your earlier comment 
about lamps and pumps being different.
So when lamps and pumps are handled differently,
treat them differently, but not until then.
The only differences between controlPumps() and controlLamps() in the 
[current master branch](https://github.com/mayaculpa/hapi/tree/2e7d15d0) of 
[hapi_controls.ino](https://github.com/mayaculpa/hapi/blob/2e7d15d/src/dumb_module/arduino/hapinode/hapinode.ino) are:
- function name
- comments
- whitespace

So I refactored the common code to a separate function.
It is an small incremental improvement.

When the needs changes, we'll change the code, but not until then.

> We need to maintain separation of these.

That's why I left the controlPumps() and controlLamps() separate
instead of combining into only function. 
Avoiding that consolidation now might be a bit of YAGNI impurity on my part.

> My suggestion before was that if we went to a common piece of
> code, that a definition of the parameters of that code was set
> (e.g. turn-on time, duration, turn-off time etc)

There might be some nuance in your use of the word "set".
I am interpreting your use of it to mean that 
the definition of the parameters will never (or almost never) change.

In the past, it was a high virtue for me to anticipate the future needs of code.
So in this example, I would not consolidate the functions into one
until I absolutely, positively knew that they would never
change as far as the parameters are concerned.

This is exactly what YAGNI is about. 
YAGNI blew my mind the first time I heard about it.
I thought it was nonsense, violating my judgment
about what the overall quickest easiest way to get the finished 
program done, not some short-sighted optimization for the present.
I would gladly do more work now to avoid much work later.
YAGNI tells me that such judgment is wrong more often that it is right;
that doing more anticipatory work now just creates even more work later,
and unnecessarily so. 

I am slow to change, but I am changing.
I am warming up slowly to YAGNI, hence commit 173f039.
When the needs become different, let's change the code, but not until then.
For now, the common part is refactored out.

Thanks to Jason Green (@gJigsaw) for talking about this at the last Python meeting.

---

I wonder about comparing YAGNI with lean manufacturing that has
minimal inventory instead of large inventory in anticipation of future needs.

---

By the way, [rebasing](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) 
is powerful, fun, dangerous, and very useful. @PedroSFreitas has used it.

**Comment by james-prior** [comment]
@ozarchie wrote: 

> The reason that the factor was 10 was that the loop had a delay
> at the end. So the loop only executed once every 100mS - so
> 10*100 = 1000mS. It was really just a placeholder until proper
> time functions and delay() functions were implemented.

> The reason for the delay() is to reduce the number of polls to
> approximately 10/s.

Thanks for confirming what I was struggling with figuring out in early commits
and had figured out by later commits.

**Comment by james-prior** [comment]
@ozarchie wrote:

> Delay() is actually a lower power mode that continually polling.

Cool! I did not know that. Of course delay() sucks for other reasons.

**Comment by ozarchie** [comment]
Hi James, I have changed quite a lot of the code to implement the time
related placeholders. I'm not sure that they have been accepted yet. They
are based on arduino libraries so perhaps you could review them. Cheers
Archie

**Comment by james-prior** [comment]
New commit resolved merge conflicts.

**Comment by james-prior** [comment]
@ozarchie wrote:

> ... I have changed quite a lot of the code to implement the time related placeholders. 

> ... so perhaps you could review them.

If you are talking about the pull request #97,
please repost there so that your comments
are not lost here.

**Comment by james-prior** [comment]
Merged and pushed the easy stuff from @ozarchie's pull request #97.

The other stuff should be discussed on the [conversation](https://github.com/mayaculpa/hapi/pull/97) for pull request #97.

**Pull request merged**
