### PR TITLE
smart_module.py: SmartModule.connect_influx(): Simplify with try/except.

### PR DESCRIPTION
**Pull request by james-prior**
I do not know if this works. It is an experiment, so please scrutinize it and test it.

If it works, it yields a nice simplification,
avoiding the need to search through database names.

### CODE REVIEW

**Comment by PedroSFreitas** [comment]
Not sure:
```
2017-05-13 14:20:18,381 - smart_module - INFO - Communicator initialized
Mock Smart Module hosting asset  HSM-WT123-MOCK wt Environment
2017-05-13 14:20:18,383 - smart_module - INFO - Performing Discovery...
2017-05-13 14:20:18,384 - smart_module - INFO - Waiting Broker information on attempt: 1.
2017-05-13 14:20:19,385 - smart_module - INFO - MQTT Broker: ArchMain.local. IP: 192.168.0.99.
2017-05-13 14:20:19,386 - smart_module - INFO - Connecting to ArchMain.local. at 192.168.0.99.
2017-05-13 14:20:20,387 - smart_module - INFO - Connected with result code 0
$SYS/broker/clients/total 0
2017-05-13 14:20:25,922 - smart_module - INFO - No Scheduler found. Becoming the Scheduler.
2017-05-13 14:20:25,923 - smart_module - INFO - Loading Schedule Data...
2017-05-13 14:20:25,924 - smart_module - INFO - Schedule Data Loaded.
2017-05-13 14:20:25,924 - smart_module - INFO -   Loading seconds job: System Status
2017-05-13 14:20:25,925 - smart_module - INFO - Scheduler program loaded.
2017-05-13 14:20:25,925 - smart_module - INFO - Site data loaded.
$SYS/broker/clients/total 1
Running command self.smart_module.on_query_status()
STATUS/QUERY I might need to know how you are!
STATUS/RESPONSE [{'memory': {'cached': 1054945280, 'used': 2053513216, 'free': 603156480}, 'disk': {'total': 52472872960, 'free': 36957638656, 'used': 12819345408}, 'network': {'packet_recv': 2625782, 'packet_sent': 2554172}, 'time': 1494696036.639456, 'hostname': 'ArchMain', 'boot': '2017-05-12 22:04:25', 'cpu': {'percentage': 2.8}, 'clients': 1}]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 2630, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 1410, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 926, in loop
    rc = self.loop_read(max_packets)
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 1209, in loop_read
    rc = self._packet_read()
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 1802, in _packet_read
    rc = self._packet_handle()
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 2278, in _packet_handle
    return self._handle_publish()
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 2464, in _handle_publish
    self._handle_on_message(message)
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 2624, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/home/psf/Github/hapi/src/smart_module/communicator.py", line 114, in on_message
    self.smart_module.push_sysinfo("system", self.smart_module.last_status)
  File "smart_module.py", line 288, in push_sysinfo
    conn.write_points(json)
  File "/usr/lib/python2.7/site-packages/influxdb/client.py", line 411, in write_points
    tags=tags, protocol=protocol)
  File "/usr/lib/python2.7/site-packages/influxdb/client.py", line 461, in _write_points
    protocol=protocol
  File "/usr/lib/python2.7/site-packages/influxdb/client.py", line 292, in write
    headers=headers
  File "/usr/lib/python2.7/site-packages/influxdb/client.py", line 253, in request
    raise InfluxDBClientError(response.content, response.status_code)
InfluxDBClientError: 404: {"error":"database not found: \"system\""}
```

**Comment by PedroSFreitas** [comment]
I've performed two tests: 
1. if the database already exists - > PASSED.
2. if not -> FAILED.

**Comment by james-prior** [comment]
@PedroSFreitas, Thanks for testing my experiment.

The obvious thing to do is to figure out what the last version that works is, then use that code.

**Comment by PedroSFreitas** [comment]
> The obvious thing to do is to figure out what the last version that works is, then use that code.

@james-prior for sure. It simplify beautifully the code.
Not sure if you read my previous comment on another pull request that was merged. The docs are here: http://influxdb-python.readthedocs.io/en/latest/exceptions.html. If you notice the url, it says "latest". Which refers to Release:	4.1.0. And you can check it here too: http://influxdb-python.readthedocs.io/en/latest/index.html
Here is the output of pip:
```
$ pip2 search influxdb                                                                                                                           [...]
[...]
influxdb (4.1.0)                       - InfluxDB client
  INSTALLED: 4.1.0 (latest)
[...]
```

I'm hoping we're missing something here because as I said, it's indeed a nice piece of code.

[EDIT]
Forgot to mention the tests were made using 4.1.0.

**Comment by james-prior** [comment]
@PedroSFreitas wrote:

> I'm hoping we're missing something here ...

We probably are missing something. I do not know what that something is.

> ... it's indeed a nice piece of code.

Thanks. EAFP is one of Python's superpowers.
But working code beats pretty code.
When we know the last commit that was working,
then we can focus our attention on the differences
between the working code and the code that is not working.

Would it help to add diagnostics to show what value
of database_name is passed to the .connect_influx() method?

By the way, the lines from /usr/lib/python2.7/site-packages/influxdb/client.py
that you showed above, do not match the code I have.

    (hapi) jp@hapi:~/anaconda3/envs/hapi/lib/python2.7/site-packages/influxdb$ conda list
    # packages in environment at /home/jp/anaconda3/envs/hapi:
    #
    influxdb                  4.1.0                     <pip>
    openssl                   1.0.2k                        2  
    pip                       9.0.1                    py27_1  
    python                    2.7.13                        0  
    python-dateutil           2.6.0                     <pip>
    pytz                      2017.2                    <pip>
    readline                  6.2                           2  
    requests                  2.14.2                    <pip>
    setuptools                27.2.0                   py27_0  
    six                       1.10.0                    <pip>
    sqlite                    3.13.0                        0  
    tk                        8.5.18                        0  
    wheel                     0.29.0                   py27_0  
    zlib                      1.2.8                         3  
    (hapi) jp@hapi:~/anaconda3/envs/hapi/lib/python2.7/site-packages/influxdb$ python -c 'print "".join(str(i) + line for i, line in enumerate(open("/home/jp/anaconda3/envs/hapi/lib/python2.7/site-packages/influxdb/client.py")) if i in (411, 461, 292, 253))'
    253
    292        elif protocol == 'line':
    411        :param points: the list of points to be written in the database
    461    def _write_points(self,
    
    (hapi) jp@hapi:~/anaconda3/envs/hapi/lib/python2.7/site-packages/influxdb$ md5sum /home/jp/anaconda3/envs/hapi/lib/python2.7/site-packages/influxdb/client.py
    5ac6ba69a21155e333668ea7475817ac  /home/jp/anaconda3/envs/hapi/lib/python2.7/site-packages/influxdb/client.py
    (hapi) jp@hapi:~/anaconda3/envs/hapi/lib/python2.7/site-packages/influxdb$ 

---

Something that bothers me is having bad code in master branch. Perhaps risky code (like my experiment) should first be merged to a development or testing branch and merged to master only after the code is known to be good.

**Comment by PedroSFreitas** [comment]
> By the way, the lines from /usr/lib/python2.7/site-packages/influxdb/client.py

md5 is matching (I may probably have pasted something wrong on the previous comment [influx error])
```
$ md5sum /usr/lib/python2.7/site-packages/influxdb/client.py
5ac6ba69a21155e333668ea7475817ac  /usr/lib/python2.7/site-packages/influxdb/client.py
```

> Something that bothers me is having bad code in master branch

I've touched on this subject with Tyler.

> EAFP is one of Python's superpowers.

Yeah, I've noticed this on some of your previous commits.
Important to note that I'm learning a lot from you and Tyler.

**Comment by PedroSFreitas** [comment]
Just to "improve" our conversation, I've set up a virtual environment using: https://wiki.archlinux.org/index.php/Python/Virtual_environment
Let me know if you have any tips.

**Comment by james-prior** [comment]
I am familiar with virtualenv and use it much also.

[UPDATED:]
I can install the influxdb, paho-mqtt, psutil, RPi.GPIO, schedule, and zeroconf libraries,
but how does one install the SDL_DS3231 library?

I have the same successes and failures installing the above libraries with 
both conda virtual environments and virtualenv.

**Comment by TylerReedMC** [comment]
You only need the SDL library of you're running the actual real-time clock. You can find it here: https://github.com/switchdoclabs/RTC_SDL_DS3231/blob/master/SDL_DS3231.py

**Comment by PedroSFreitas** [comment]
And just as a note, @james-prior you even made a pull request for that project 😄

**Comment by james-prior** [comment]
The problem is one of documentation, and unstated assumptions.

From [The Zen of Python](https://www.python.org/dev/peps/pep-0020/):

    Explicit is better than implicit.

It's time to make explicit what has been implicit.

---

For example, with the regards to the SDL library,
should one install it as a library with pip,
either system wide or in a virtual environment,
or should one just copy one file from the project into some directory?
Whatever the answer is, it needs to be documented.

**Comment by PedroSFreitas** [comment]
@james-prior 
> Something that bothers me is having bad code in master branch. Perhaps risky code (like my experiment) should first be merged to a development or testing branch and merged to master only after the code is known to be good.

Now you can create pulls to `dev`. We'll test it and if everything is okay we'll merge it with `master`.
Let me know if you have any further tips for us. 👍

**Comment by james-prior** [comment]
@PedroSFreitas wrote:

> @james-prior
> 
> > Something that bothers me is having bad code in master branch.
> > Perhaps risky code (like my experiment) should first be merged 
> > to a development or testing branch and merged to master only 
> > after the code is known to be good.
>
> Now you can create pulls to dev.

You are right. Doh! I do not know why I did not think of that.
Furthermore, if I recall correctly, the dev branch has existed for some time.
So I could have issued a pull request for the dev branch when I wrote.
Thanks for reminding me.

> Let me know if you have any further tips for us. :+1:

I do. Some deserve more attention than a comment on a closed branch,
so I will show them elsewhere.

You already did one of them, updating the except syntax;
changing "except Exception, ..." to "except Exception as ...".

**Comment by PedroSFreitas** [comment]
**@james-prior commented**
> I do. Some deserve more attention than a comment on a closed branch,
> so I will show them elsewhere

I understand. So what would you prefer? Open an Issue? Maybe via e-mail? Hangout? IRC?
It would be really interesting to have a more direct means of communication with you. Probably because I'd squeeze all your knowledge for my own sake lol... in a good way though 😄

**Comment by james-prior** [comment]
@PedroSFreitas wrote:

> @james-prior commented
>
> > I do. Some deserve more attention than a comment on a closed branch,
> > so I will show them elsewhere
> 
> I understand. So what would you prefer?

It depends.

> Open an Issue?

Opening new issues and comments in new pull requests
are two such places to discuss stuff that needs attention.
I already did that with the if/else simplification for the Arduino code.

> Maybe via e-mail?

Plain text email that is publicly archived and can be read without registration
is the best place for conversations. When no registration is required,
search engines index the email, so people find your conversations and 
project who did not even know you existed. One can have small terse 
and long thoughtful email posts. The long thoughtful stuff happens
little on real-time chatty things like IRC. Although it's not for a project,
an example of a publicly archived mailing list is
[COhPy's archive](https://mail.python.org/pipermail/centraloh/).

> Hangout?

I prefer to avoid proprietary services. All your base are belong to us.
If you haven't figured out who the [mark](https://en.wikipedia.org/wiki/Confidence_trick) is,
you are probably it.

> IRC?

Interruptions are terribly destructive of productivity for programmers,
so I avoid real-time chatty things such as IRC.

Email is patient. With email, I can get into the [flow](https://en.wikipedia.org/wiki/Flow_%28psychology%29)
pondering code, without being interrupted.
Plain text email plays nice with things like grep, sed, awk, and friends.
We're back to the Unix philosophy.

---

By the way, you can pick up things from the scribbles on the COhPy mailing list archives.
For example, peruse [[CentralOH] 2013-06-07 道場 Scribbles 落書/惡文?](https://mail.python.org/pipermail/centraloh/2013-June/001718.html)

**Comment by PedroSFreitas** [comment]
Thanks for the detailed answer.

> Email is patient. With email, I can get into the flow
> pondering code, without being interrupted.

That indeed is **true.** I have noticed this on a few other things as well.
I'm not sure how or even if we can "set up" a public mail list **now**, rather than using some "proprietary" service. Then again, if you have any further advices or tips, please let me know. It's totally a new territory for me (learning every day).

In the meanwhile, until figure out/set up a few things, we could stick with Github? Just an idea, you could "Watch'd" the repo so on every Issue or Pull you'll receive a notification? There is even the possibility to put you as a member maybe? That way you could push changes directly to the repository and such... Anyway, just trying to find something in the middle-term for now!

**Comment by james-prior** [comment]
@PedroSFreitas wrote:

> I'm not sure how or even if we can "set up" a public mail list now, ...

I also don't know how to set up a public mailing list,
but I know that it can be done.
The hard part is making the decision, which is Tyler's to make.
With a decision to do it, how it would be done is a boring implementation detail.

> In the meanwhile, until figure out/set up a few things, we could stick with Github? 

That's what we are already doing.

**Comment by PedroSFreitas** [comment]
> That's what we are already doing.

The follow up is more interesting:
> you could "Watch'd" the repo so on every Issue or Pull you'll receive a notification? **There is even the possibility to put you as a member maybe?** That way you could push changes directly to the repository and such... Anyway, just trying to find something in the middle-term for now!

👍

**Comment by TylerReedMC** [comment]
We have archived, searchable, real-time, asynchronous (aka patient) communications for the entire team that supports 1-to-1 and channel messaging with file sharing, comment flagging and online status. It integrates with our Kanboard scheduling system as well as Jenkins. When I post this comment it will be added as a comment to this issue in Kanboard and notification will be sent to the Platform Engineering channel on the comm server. It's wide open to the public and requires only an email address to access, which is nice and transparent but means we'll likely have to curate out the jerk-offs and spammers. It also support s access via SmartPhone.

I setup the comm server to avoid having discussions exactly like this one, i.e. communication in comment threads that is completely irrelevant to the actual issue. (Also note that only the development people on the team are actively using GitHub.)

I'm not a closed-minded person, just trying to be efficient. Explain to me how adding a public email list will increase our capabilities enough to justify the administrative overhead of another comm tool and we'll do it.

**Comment by ozarchie** [comment]
Hi All,
I am much happier using the infrastructure that Tyler already has in place.
In future, I will keep my responses to that forum, and create tasks in KB.
I will move the discussion with James to a task, and restrict responses to
PD or PE.
I especially support the open nature of that approach.
Cheers
Archie

**Comment by james-prior** [comment]
More tasty plants and more happy people!
It's the [network effect](https://en.wikipedia.org/wiki/Network_effect) on steroids!

The benefits are:
- more people finding this project
- more interest in this project
- more people reading about this project
- more people using this project
- more people talking about this project
- more people contributing to this project, which leads to:
    - higher quality
    - more features
    - fewer flaws
- more tasty plants!
- more happy people eating more tasty plants!

Open source development happens in the open.
That openness has a network effect on steroids.

Search engines are key to this.
People find us through search engines.
If search engines can not find us,
people will not even know we exist.
The search engines need to be able see us.
Turn offs for search engines are:
- registration
    - sites that require registration are hidden to search engines
    and most of the world you want to reach
    - tilt!
    - game over!
    - Do not pass "GO"!
- javascript thwarts many search engines

The complement of open systems are [information silo](https://en.wikipedia.org/wiki/Information_silo)s.
Information silos are like [roach motel](https://en.wikipedia.org/wiki/Roach_Motel_%28insect_trap%29)s.
Information checks in, but does not check out.
        
> ... the cost

Administrivia

- the administration burden to you is insignificant
- delegate to someone
- someone has already volunteered
- ask for someone to take care of the mailing list and it will just happen

**Comment by TylerReedMC** [comment]
What information needs to be publicly accessible that isn't already publicly accessible?

**Comment by james-prior** [comment]
On Tue, 30 May 2017 11:00:46 -0700, Tyler Reed <notifications@github.com> wrote:

> What information needs to be publicly accessible that isn't already publicly accessible?

That which requires registration (and login) for anyone,
including search engines, to read.
Also, that which requires javascript to access.

Which search engines can read and index your informatino?
Without the search engines knowing your information,
it will be hidden to most of the world.

The last time I visited your mattermost server
at the address you gave me,
it required javascript and registration to login.
I just tried again with same results.

**Comment by TylerReedMC** [comment]
The MatterMost server is available to the public at: http://104.131.99.114:8065/proddevelopment

All digital output from this project team is available to the public and to search engines (without registration of javascript) including code, hardware designs, documentation and the production schedule. We have no need for our private and/or team coordination conversations to be indexed by a search engine as it would benefit no one. Nor are we reverting to less capable communications technologies such as email lists, faxing or smoke signals.

If you don't want to collaborate with the team using the infrastructure that we've adopted, that's up to you. The fact that we're debating this via comments on an unrelated issue is pure silliness.

**Pull request merged**
