### PR TITLE
src/dumb_module/arduino/hapinode/hapinode.ino: flashLED(): Simplified.

### PR DESCRIPTION
**Pull request by james-prior**
This might be one of those things where valid C break Arduino's way of doing things.

So test.

### CODE REVIEW

**Comment by james-prior** [comment]
I wonder if the % 100 causes an occasional minor bug.
Does it happen about every 50 days?

[UPDATED]
Studying other loopcount code, I see that the answer is no
because loop count is reset frequently:

    if ((loopcount++ % 3600) == 0) ...
        ...
        loopcount = 0;

but that makes me wonder if it is a bug to increment loopcount in two different places.

**Comment by TylerReedMC** [comment]
It happens every 100 times through the loop, so I'm guessing it's about every second or so. Yes?

**Comment by james-prior** [comment]
@TylerReedMC wrote: 

> It happens every 100 times through the loop, so I'm guessing it's about every second or so. Yes?

We might be talking about different issues.

It is curious that the same global variable loopcount is incremented in two 
different functions, loop() and flashLED().
If both of those functions are called (polled?), could fun things happen?

**Comment by TylerReedMC** [comment]
Actually, I would check the loopcount % 100 value in the loop function and just call flashLED if it passes the condition. That would eliminate the double increment and minimize calls to flashLED to only when necessary.

**Pull request merged**
