### PR TITLE
hapifirmware.ino: Miscellaneous refactorings.

### PR DESCRIPTION
**Pull request by james-prior**
In particular,
commit 115b104 needs review to determine if it fixed a bug or created a bug (or both or neither).

### CODE REVIEW

**Comment by ozarchie** [comment]
Hi James,
HAPIfirmware is presently a placeholder.
We were going to remove it as its focus is on general arduino connection -
rather than WiFi connections.
As such it has limitations, but also advantages (CAT5, serial, RS485, modem
connections).
It may surface again, but at this stage I am not looking at further
development.
If you would like to take it forward that would be great.
I have tried to separate the code as much as possible, so that MQTT, time,
etc are isolated.
Cheers
Archie

**Review by TylerReedMC — COMMENTED** [review]
#if defined(RTU_USB) || defined(RTU_UNO)
Doesn't this equate the UNO platform with USB connectivity?

**Review by TylerReedMC — COMMENTED** [review]
Rather than hard-coded 0 and 5, can we somehow get the min and max values from the pin control enum that you created for this merge?

**Review by TylerReedMC — COMMENTED** [review]
The first is easier for me to understand. I've always programmed constant/value comparisons in a style of: variable <compared to>  constant/value.

**Comment by james-prior** [comment]
@TylerReedMC wrote:

> #if defined(RTU_USB) || defined(RTU_UNO)
> Doesn't this equate the UNO platform with USB connectivity?

I do not know.
I also do not know if equating UNO platform with USB connectivity is desirable or not.
That particular refactoring should have the same behavior as the earlier code,
although looking at it closer now, I see that in the old code if both RTU_USB and RTU_UNO
were defined, there would be two while statements with opening '{',
but only one closing '}' later, so the compiler would likely crash.
The new code would not crash if both RTU_USB and RTU_UNO are defined.
I do not know if not crashing is desirable or not.

Relevant section of output from git diff follows.

    -#ifdef RTU_USB
    -  while ((Serial.available() > 0) && !stringComplete) {
    -    inChar = (char)Serial.read();  // read the bytes incoming from the client:
    -#endif
    -#ifdef RTU_UNO
    -  while ((Serial.available() > 0) && !stringComplete) {
    +#if defined(RTU_USB) || defined(RTU_UNO)
    +  while (Serial.available() > 0 && !stringComplete) {
         inChar = (char)Serial.read();  // read the bytes incoming from the client:
    -#endif

**Comment by james-prior** [comment]
@TylerReedMC asked:

> Rather than hard-coded 0 and 5, can we somehow get the
>  min and max values from the pin control enum that you created for this merge?

I know of no way within C and its preprocessor to do that.
One could have external processors to figure that out.
The awkwardness of doing so would outweigh its benefits.

A following commit of a four-way merge that I have not pushed,
explores this even more than you wrote about.

Then, after that is resolved, I look forward to a discussion with Pedro
about how he would do that in Python, but that's for later.

**Comment by james-prior** [comment]
@TylerReedMC wrote:

> The first is easier for me to understand.

Please quote just enough context so that I know what you are talking about.

**Comment by james-prior** [comment]
@ozarchie wrote:

> HAPIfirmware is presently a placeholder. 
> We were going to remove it ...

Is there duplicate code in the hapifirmware and hapinode directories?
Are there changes in this pull request
that are also relevant for files in the hapinode directory?

**Comment by TylerReedMC** [comment]
Sorry, it was a comment on what I found easier to read.
for (int i = 0; i < NUM_DIGITAL; i++) {
   if (0 < pinControl[i] && pinControl[i] < 5) {
     assembleResponse(response, (String)i, (String)digitalRead(i));
   }
 }

I prefer variable-comparator-value to the above structure.

**Comment by james-prior** [comment]
in the message for commit d835d98 I asked:

> Which of the following is easier for you to understand?
>
>     if (pinControl[i] > 0 && pinControl[i] < 5)
>     if (0 < pinControl[i] && pinControl[i] < 5)

to which @TylerReedMC wrote:

> The first is easier for me to understand.
> I've always programmed constant/value comparisons in a style of: variable constant/value.

I write most of my comparisons as variable : value, but not all.
For range checks, it is easier for me to read by arranging the values
in their putative order. That is, reading from left to right,
I progress from low to high values.

I wondered if there were people who always do variable : value order,
which is why I asked my question in the message for commit d835d98.
Thanks for playing.
Of course, we are both correct, because each of us
is the world's foremost authority on what is easiest for each of us to read.
Likewise for what our [favorite color](https://www.youtube.com/watch?v=dPOyOM7wxlE) is.

By the way, in C one has to write the in-between value twice.
In Python, one can write the in-between value once. For example:

    if 0 < pinControl[i] < 5:

**Pull request merged**
