### PR TITLE
src/smart_module/smart_module.py: Disable month and year scheduling.

### PR DESCRIPTION
**Pull request by james-prior**
It seems that the schedule library does not support month and year scheduling.

Maybe it would be good to add month and year to schedule,
but that is outside the scope of this project.

### CODE REVIEW

**Comment by TylerReedMC** [comment]
Just FYI, all pulls (except this one) are running successfully on the Pi.

**Comment by james-prior** [comment]
On Thu, 11 May 2017 04:36:52 -0700, Tyler Reed <notifications@github.com> wrote:

> Just FYI, all pulls (except this one) are running successfully on the Pi.

Thanks, that's good to know, especially since I have been coding 
without running it.

**Comment by james-prior** [comment]
@TylerReedMC wrote:

> Just FYI, all pulls (except this one) are running successfully on the Pi.

Uh oh, I missed the part about "(except this one)".
Did you mean that this commit failed, or just had not been tested yet?

**Comment by TylerReedMC** [comment]
Just hadn't been tested yet.

**Pull request merged**
