### PR TITLE
communicator.py: Trim trailing whitespace.

### PR DESCRIPTION
**Pull request by james-prior**
Easy merge.

### CODE REVIEW

**Comment by PedroSFreitas** [comment]
Thanks, James.

**Comment by james-prior** [comment]
Hi @PedroSFreitas,

Unix is a tool builder's culture.
Think of Lego bricks.
Explore how the following bricks are combined.

    grep -r '  *$' *
    grep -rl '  *$' *
    vi -o `grep -rl '  *$' *`  ;# <Esc>:qa to get out of vi
    find * -name '*.py' -print
    find * -name '*.py' -exec grep '  *$' {} \;
    find * -name '*.py' -exec grep -l '  *$' {} \;
    find * -name '*.py' -exec grep -l '  *$' {} \; | while read f; do t=`mktemp`; echo sed -e 's/  *$//' "$f" "$t";echo mv -f "$t" "$f";done
    find * -name '*.py' -exec grep -l '  *$' {} \; | while read f; do t=`mktemp`; sed -e 's/  *$//' <"$f" >"$t";mv -f "$t" "$f";done

**Comment by PedroSFreitas** [comment]
> Unix is a tool builder's culture.

Not sure, but I believe I read a similar _definition_ of Unix on K&R. Or maybe on another book.

**Comment by james-prior** [comment]
@PedroSFreitas wrote: 

> Not sure, but I believe I read a similar definition of Unix on K&R. Or maybe on another book.

The two following books are excellent.

- [The UNIX Programming Environment](https://en.wikipedia.org/wiki/The_Unix_Programming_Environment)
  This is a tutorial for doing things the unix way,
  even though some of the commands are irrelevant now.
- [The Unix Philosophy by Mike Gancarz](https://duckduckgo.com/html?q=Mike%20Gancarz%20the%20unix%20philosophy)
  great book for explaining the philosophy.
  It is not a tutorial.
  There is a newer version called [Linux and the Unix Philosophy: Mike Gancarz](https://duckduckgo.com/html?q=Mike%20Gancarz%20linux%20and%20the%20unix%20philosophy).
  I have not read the newer version.

I do not know if any of the above books say "Unix is a tool builder's culture",
but they sure live it.

**Pull request merged**
