### PR TITLE
smart_module.py: Scheduler.prepare_jobs(): Speculative refactoring plus more.

### PR DESCRIPTION
**Pull request by james-prior**
Other eyeballs are needed to scrutinize this code.

I went far beyond mere refactoring, making many assumptions of which at least
one is likely to be wrong, so this code should be considered speculative.
If it works, that's fine.
If not, I hope it provokes thought about what we want .prepare_jobs() to do.

prepare_jobs() had repeated code patterns, so I refactored it,
then I tried to generalize it and minimize special cases.

Added capability to handle year stuff.
I do not know if that is valid to do or not.

Although schedule.every(job.interval).months.do(self.run_job, job) was
commented out, for consistency, that capability was added.
I do not know if that is valid to do or not.

What does a value of -1 for job.interval mean?

For job.interval <= -1,
does it make sense to do stuff for weeks, months, or years as I allow?

### CODE REVIEW

**Comment by TylerReedMC** [comment]
Thanks James. I'll test this evening and let you know what I find.

**Comment by PedroSFreitas** [comment]
> What does a value of -1 for job.interval mean?


Actually `job.interval > -1` is an old piece of code (probably a bug) since it would allow it to be 0.
We cannot have jobs running at an interval of `0`; I believe, but could be wrong here.

I'd vote for `job.interval >= 1` (`job.interval > 0`).
If that addresses your question.

[EDIT]: removed misleading piece of information.

**Comment by james-prior** [comment]
Neverminding the comparisons, I am ignorant of the meaning of the -1 value. 

With self.interval (of a Scheduler.Job object) being deliberately initialized to -1,
I wonder what the -1 means. Possibilities include a sentinel value to indicate
something special, or that it was given a deliberately invalid value
to indicate that it did not have a meaningful value (yet). 
Your comment seems to indicate the latter, and that the job.interval > -1 test is [LBYL](https://docs.python.org/2/glossary.html#term-lbyl) for schedule.every(job.interval).

If the latter is the case, it would probably be better to initialize .interval of Job objects with None.

Let's document whatever we decide about .interval values. 
1. What are its values?
2. What do they mean?

---

By the way, Python makes it easy to do 
[EAFP](https://docs.python.org/2/glossary.html#term-eafp) instead of LBYL. 
For EAFP, one would put the schedule.every(job.interval) call in a try block 
and it would raise an exception if given an unreasonable value. 
An except block would handle the "else" code. 
The benefit of EAFP would be that only schedule.every needs to know 
what's valid or not, isolating that knowledge to within the object.

One of the many [intros about EAFP v LBYL](https://duckduckgo.com/html?q=d%3Aeafp%20lbyl%20python) is [here](https://github.com/james-prior/cohpy/blob/master/20170424-cohpy-lbyl-v-eafp.ipynb).

Let's get it working correctly with LBYL before considering EAFP. 
If 0 is not a valid value for schedule.every(), 
then we should be testing job.interval > 0 or job.interval >= 1 
instead of job.interval > -1.

**Comment by TylerReedMC** [comment]
-1 is kind of a holdover. I was using it to denote that the particular time interval had no relevance. In earlier code, 0 was relevant as I was formatting timing more like cron jobs afair. By now, 0 has also become irrelevant, if we all agree that we will only schedule jobs using a single time unit (as it is now). Initializing to None would be fine.

**Comment by james-prior** [comment]
How well would a value of None play with the database? Do we need to stick with numbers for the database?

**Pull request merged**
